# Generated by Django 4.2.6 on 2023-10-31 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_type', models.CharField(max_length=25)),
                ('acc_no', models.CharField(max_length=10, unique=True)),
                ('acc_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('acc_status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], default='pending', max_length=20)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
