# Generated by Django 4.2.7 on 2023-11-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanagement', '0003_alter_account_acc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_no',
            field=models.BigIntegerField(),
        ),
    ]
