# Generated by Django 4.2.7 on 2023-11-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('manager', 'manager'), ('staff', 'staff'), ('customer', 'customer')], max_length=10),
        ),
    ]
